title: "Ecosystem of Systematic Reviews"
description: "Towards an ecosystem of systematic reviews/meta-analyses on carbon pricing"
remote_theme: just-the-docs/just-the-docs
#url: "https://yourcustomdomain.com"

# Navigation
nav_order: 1
search_enabled: true
