title: "Ecosystem of Reviews"
description: "A structured repository for systematic reviews on climate change."
remote_theme: just-the-docs/just-the-docs
#url: "https://yourcustomdomain.com"

# Navigation
nav_order: 1
search_enabled: true
